version: "3.6"

services:
  db:
    image: postgres
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "expenses"
      POSTGRES_USER: "expenses"
      POSTGRES_PASSWORD: "123456"
  # backend:
  #   build: ./
  #   depends_on:
  #     - "db"
  #   ports:
  #     - 8888:8888
  #   environment:
  #     - PORT=8888
  #     - POSTGRES_HOST=db
  #     - POSTGRES_DB=expenses
  #     - POSTGRES_USER=expenses
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_PORT=5432
  #   volumes:
  #     - ./:/app
