// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/leogsouza/expenses-tracking/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *Reader) Find(id entity.ID) (entity.Account, error) {
	ret := _m.Called(id)

	var r0 entity.Account
	if rf, ok := ret.Get(0).(func(entity.ID) entity.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.ID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Reader) FindAll() ([]entity.Account, error) {
	ret := _m.Called()

	var r0 []entity.Account
	if rf, ok := ret.Get(0).(func() []entity.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
