// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/leogsouza/expenses-tracking/backend/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *Reader) Find(id entity.ID) (entity.Transaction, error) {
	ret := _m.Called(id)

	var r0 entity.Transaction
	if rf, ok := ret.Get(0).(func(entity.ID) entity.Transaction); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Transaction)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.ID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *Reader) FindAll() ([]entity.Transaction, error) {
	ret := _m.Called()

	var r0 []entity.Transaction
	if rf, ok := ret.Get(0).(func() []entity.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByType provides a mock function with given fields: tt
func (_m *Reader) FindAllByType(tt string) ([]entity.Transaction, error) {
	ret := _m.Called(tt)

	var r0 []entity.Transaction
	if rf, ok := ret.Get(0).(func(string) []entity.Transaction); ok {
		r0 = rf(tt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
